# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json

providers:  # one or more models, with optional temperature and system instructions
  - id: "vertex:gemini-1.5-flash"
  - id: "vertex:gemini-2.0-flash"

prompts:
  - file://prompt_template.txt

tests:  # Promptfoo will generate a separate prompt for each record in this dataset based on the prompt template above
  - file://dataset.jsonl

defaultTest:  # The rules for scoring each model response
  assert:
    - type: answer-relevance
      value: "Check if the response adheres to the instructions in the prompt"
      threshold: 0.5
