name: talk2_docs
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  aligned_dialog: 0.0.6
  aligned_tooltip: 0.0.1
  auto_size_text: 3.0.0
  cached_network_image: 3.3.1
  data_table_2: 2.5.10
  easy_debounce: 2.0.1
  equatable: 2.0.5
  file_picker: ^8.0.7
  flutter_animate: 4.5.0
  flutter_cache_manager: 3.3.1
  flutter_spinkit: 5.2.0
  font_awesome_flutter: 10.7.0
  from_css_color: 2.0.0
  go_router: 12.1.3
  google_fonts: 6.1.0
  google_sign_in: ^6.2.1
  http: 1.2.1
  intl: 0.19.0
  json_path: 0.7.2
  lottie: 2.7.0
  mime_type: 1.0.0
  page_transition: 2.1.0
  path_provider: 2.1.3
  path_provider_android: 2.2.5
  path_provider_foundation: 2.4.0
  path_provider_platform_interface: 2.1.2
  provider: 6.1.2
  shared_preferences: 2.2.2
  shared_preferences_android: 2.2.1
  shared_preferences_foundation: 2.3.4
  shared_preferences_platform_interface: 2.3.1
  shared_preferences_web: 2.2.1
  simple_gradient_text: 1.2.3
  sqflite: 2.2.6
  timeago: 3.6.1
  url_launcher: 6.3.0
  url_launcher_android: 6.3.4
  url_launcher_ios: 6.3.1
  url_launcher_platform_interface: 2.3.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dependency_overrides:
  http: 1.2.1
  uuid: ^4.0.0
  win32: 5.5.1

dev_dependencies:
  flutter_lints: 4.0.0
  lints: 4.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/

  fonts:
    - family: 'GoogleSans'
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.ttf
        - asset: assets/fonts/GoogleSans-Italic.ttf
          style: italic
        - asset: assets/fonts/GoogleSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/GoogleSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/GoogleSans-BoldItalic.ttf
          weight: 700
          style: italic
    - family: 'GoogleSansText'
      fonts:
        - asset: assets/fonts/GoogleSansText-Regular.ttf
        - asset: assets/fonts/GoogleSansText-Italic.ttf
          style: italic
        - asset: assets/fonts/GoogleSansText-Medium.ttf
          weight: 500
        - asset: assets/fonts/GoogleSansText-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/GoogleSansText-Bold.ttf
          weight: 700
        - asset: assets/fonts/GoogleSansText-BoldItalic.ttf
          weight: 700
          style: italic

  
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

